# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Petme' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Petme
  pod 'Firebase/Core'

  # Firebase Database
  pod 'Firebase/Database'

  # Firebase Auth
  pod 'Firebase/Auth'

  # Firebase Storage
  pod 'Firebase/Storage'
 
end
